
print("How to japa to Canada from Ajah")
print("Dress well look sharp")
print("Take bike or keke to Ajah roundabout")
print("Enter a bus from Ajah to Oshodi")
print("Enter another bus from Oshodi to Ikeja")
print("Hold your phone well!")
print("Take uber from Ikeja to MM International Airport")
print("Don\'t look back")
print("Survey the area")
print("Oya go home")